name: Build & Run

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: nvidia/cuda:12.4.1-devel-ubuntu22.04

    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: apt-get update && apt-get install -y build-essential cmake git

      - name: Build ${{ matrix.build_type }}
        run: |
          mkdir -p build/${{ matrix.build_type }}/build
          cd build/${{ matrix.build_type }}/build
          cmake \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_INSTALL_PREFIX=../ \
            -DCUDA_PATH=/usr/local/cuda \
            -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc \
            ../../../
          make -j$(nproc)
          make install
